name: 'Build'
description: 'Builds the repository'
inputs:
  token:
    description: 'token to download artifacts'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      uses: manips-sai-org/sai2-custom-actions/sai2-dependencies-setup@main

    - name: Setup Sai2-urdfreader
      uses: manips-sai-org/sai2-custom-actions/sai2-urdfreader-setup@main
      with:
        token: ${{ inputs.token }}

    - name: Build Sai2-Model
      shell: bash
      run: |
        export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:dep/sai2-urdfreader/build/
        cd rbdl && mkdir build && cd build && cmake .. && make -j4
        cd ../../
        mkdir build && cd build && cmake -DBUILD_TESTS=ON .. && make -j4

    - name: Check build status
      shell: bash
      run: |
        cd build
        make --always-make --dry-run