name: Build master and upload artifact on a schedule

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-archive:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: build-repo
        uses: ./.github/actions/build-repo
        with: 
          token: ${{ secrets.SAI2_TOKEN }}

      - name: Copy Libraries to Archive
        run: |
          cp build/libsai2-model.a ./libsai2-model.a
          cp rbdl/build/librbdl.so.3.2.0 ./librbdl.so

      - name: Archive Sai2-model Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sai2-model-artifact
          path: |
            libsai2-model.a
            librbdl.so